apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          name: ollama
        command:
          - "/bin/sh"
          - "-c"
          - |
              OLLAMA_KEEP_ALIVE=-1 &&
              /bin/ollama serve & 
              sleep 5
              ollama pull llama3.2:1b
              wait $!
            #wget --post-data '{"model": "llama3.2:1b", "keep_alive": -1}' --header="Content-Type: application/json" http://localhost:11434/api/generate

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-ingress
  namespace: ollama
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: baie-qua.luuc.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ollama
            port:
              number: 11434