apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          name: ollama
        command:
          - "/bin/sh"
          - "-c"
          - |
              export OLLAMA_KEEP_ALIVE=-1
              export OLLAMA_LLM_LIBRARY=cuda
              export OLLAMA_KV_CACHE_TYPE=gpu
              export OLLAMA_FLASH_ATTENTION=true
              export OLLAMA_MAX_LOADED_MODELS=1
              export OLLAMA_NUM_PARALLEL=2
              /bin/ollama serve & 
              sleep 5
              ollama run llama3.3:70b ""
              wait $!
        resources:
          limits:
            nvidia.com/gpu: 3 # Demande l'utilisation d'un GPU NVIDIA
        readinessProbe:
          httpGet:
            path: /
            port: 11434
          initialDelaySeconds: 150
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
          - mountPath: /root/.ollama/models  # Le chemin où le volume sera monté dans le conteneur
            name: mon-volume
            readOnly: false
      runtimeClassName: nvidia
      volumes:
        - name: mon-volume
          hostPath:
            path: /home/tmp  # Chemin sur l'hôte
            type: Directory  # Type de volume, ici un répertoire

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-ingress
  namespace: ollama
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: sns-ia-02.goat-woodpecker.ts.net
    http:
      paths:
      - path: /resume/
        pathType: Prefix
        backend:
          service:
            name: ollama
            port:
              number: 11434