apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whisper-ingress
  namespace: whisper
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: baie-qua.luuc.fr  # Vous pouvez changer le hostname selon vos besoins
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whisper
            port:
              number: 8080