---
apiVersion: v1
kind: Namespace
metadata:
  name: whisper

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: whisper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: ghcr.io/luucfr/whisper-backend/whisper:main
        ports:
        - containerPort: 80
          name: whisper

---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: whisper
spec:
  selector:
    app: whisper
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80