apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: whisper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: ghcr.io/luucfr/whisper-backend/whisper:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: whisper
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: whisper
spec:
  selector:
    app: whisper
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

